language: go

go:
  - 1.12

os:
  - osx
  - linux

env:
  - GO111MODULE=on

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
